spring:
  cloud:
   gateway:
    routes:
      - id: spl
        uri: ${SPL_BASEURL}/serviceplanet/remote/service
        predicates:
         - Path=/spl/**
        filters:
         - ServicePlanetFilter
         - RewritePath=/spl/(?<segment>.*), /serviceplanet/remote/service/$\{segment}         