spring:
  cloud:
   gateway:
    routes:
      - id: testroute
        uri: http://httpbin.org:80
        predicates:
         - Path=/get
        filters:
         - AddRequestHeader=foo,bar
         - ServicePlanetFilter=foo,bar
      - id: spl
        uri: https://smdb-dev.workspace.witcom.de/serviceplanet/remote/service
        predicates:
         - Path=/spl/**
        filters:
         - ServicePlanetFilter
         - RewritePath=/spl/(?<segment>.*), /serviceplanet/remote/service/$\{segment}         